- name: Golang
  logo: go
  url: https://golang.org/
  color: 7FD6EA
  projects:
    - https://github.com/Matt-Gleich/fgh
    - https://github.com/Matt-Gleich/gh_fsync
    - https://github.com/Matt-Gleich/nuke
    - https://github.com/Matt-Gleich/logoru
    - https://github.com/Matt-Gleich/statuser
    - https://github.com/Matt-Gleich/desktop
    - https://github.com/Matt-Gleich/new_release
    - https://github.com/Matt-Gleich/texsch
    - https://github.com/Matt-Gleich/texsep
    - https://github.com/Matt-Gleich/contrihat
    - https://github.com/Matt-Gleich/clockhat
    - https://github.com/Matt-Gleich/cihat
    - https://github.com/Matt-Gleich/ctree
    - https://github.com/Matt-Gleich/lumber
    - https://github.com/hackclub/awesome_hackclub_auto

- name: Python
  logo: python
  url: https://www.python.org/
  color: 3C78A9
  projects:
    - https://github.com/Matt-Gleich/profile_stack
    - https://github.com/Matt-Gleich/Contribution-Hat
    - https://github.com/Matt-Gleich/RPi-Status
    - https://github.com/Matt-Gleich/Doc-Dockerfiles
    - https://github.com/Matt-Gleich/Quantum-Flip
    - https://github.com/Matt-Gleich/Photo-Sort
    - https://github.com/Team-501-The-PowerKnights/Vision2020
    - https://github.com/Team-501-The-PowerKnights/Powerknights-Slack-Bot
- name: Swift
  logo: swift
  url: https://swift.org/
  color: E45530
  projects:
    - url: https://github.com/Magnesium-Software/NukeApp
      wip: true
- name: Rust
  logo: rust
  url: https://www.rust-lang.org/
  color: DEA584
  projects:
    - url: https://github.com/Matt-Gleich/wakavis
      wip: true

- name: Dart
  logo: dart
  url: https://dart.dev/
  color: 52C0F2
  projects:
    - https://github.com/fluttercommunity/import_sorter
    - https://github.com/Matt-Gleich/local_google_fonts
    - https://github.com/banurapp/geist_flutter

- name: Flutter
  logo: flutter
  url: https://flutter.dev/
  color: 52C0F2
  projects:
    - https://github.com/Matt-Gleich/Personal-Site
    - https://github.com/banurapp/geist_flutter
    - url: https://github.com/Matt-Gleich/Hack-Club-GP
      wip: true

- name: React
  logo: react
  url: https://reactjs.org/
  color: 61DAFB
  projects:
    - url: https://github.com/Matt-Gleich/site-v2
      wip: true
    - https://github.com/Matt-Gleich/dynamic-season

- name: JavaScript
  logo: javascript
  url: https://github.com/Matt-Gleich?tab=repositories&q=&type=&language=javascript
  color: F1E05A
  projects:
    - url: https://github.com/Matt-Gleich/site-v2
      wip: true
    - https://github.com/Matt-Gleich/components
    - https://github.com/Matt-Gleich/React-Translator
    - https://github.com/Matt-Gleich/Extreme-Fib-Calc

- name: Docker
  logo: docker
  url: https://www.docker.com/
  color: 4FA1EF
  projects:
    - https://github.com/Matt-Gleich/gh_fsync
    - https://github.com/Matt-Gleich/Dockerfiles
    - https://github.com/Matt-Gleich/profile_stack
    - https://github.com/Matt-Gleich/Control-Sense-Hat
