name: Update Routes

on:
  schedule:
    - cron: '0 */1 * * *' # Run every hour

jobs:
  update_routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - uses: snok/install-poetry@v1.1.1
      - name: Install dependencies
        run: |
          cd update
          poetry config virtualenvs.create false
          poetry install --no-root -n
      - name: Run script
        run: |
          cd update
          poetry run python3 update_routes.py
      - name: Commit and push changes
        run: |
          git config --global user.email "email@mattglei.ch"
          git config --global user.name "Matthew Gleich"
          git add .
          git commit -m "⚙️ Update routes"
          git push
